import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1787824437706 implements MigrationInterface {
    name = 'Init1787824437706'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "cz_withdrawal_requests" ("cz_withdrawal_request_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "amount_coins" integer NOT NULL, "amount_usd" numeric(12,2) NOT NULL, "method" character varying(20) NOT NULL, "destination_details_encrypted" text NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "reviewed_by" uuid, "reviewed_at" TIMESTAMP WITH TIME ZONE, "rejection_reason" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b50b5e3c08f43e3ef3a9ad7d6fb" PRIMARY KEY ("cz_withdrawal_request_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38355efd1f960a92fd9bdaa302" ON "cz_withdrawal_requests" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cz_wallets" ("cz_user_id" uuid NOT NULL, "coin_balance" integer NOT NULL DEFAULT '0', "gem_balance" integer NOT NULL DEFAULT '0', "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e05b1b7b8b1c16352a331f6a117" PRIMARY KEY ("cz_user_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_wallet_transactions" ("cz_wallet_transaction_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "currency" character varying(10) NOT NULL, "type" character varying(20) NOT NULL, "amount" integer NOT NULL, "balance_after" integer NOT NULL, "source_type" character varying(30) NOT NULL, "source_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a91e9799d8a70f658f41339ab8b" PRIMARY KEY ("cz_wallet_transaction_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41210ef08979d6b04c49926426" ON "cz_wallet_transactions" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cz_users" ("cz_user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "phone" character varying(20), "password_hash" character varying(255), "google_id" character varying(255), "name" character varying(120), "gender" character varying(20), "age_range" character varying(20), "country" character varying(2), "avatar_url" character varying(500), "interests" jsonb NOT NULL DEFAULT '[]'::jsonb, "primary_goal" character varying(60), "referral_code" character varying(12) NOT NULL, "referred_by" uuid, "tier" character varying(20) NOT NULL DEFAULT 'silver', "kyc_status" character varying(20) NOT NULL DEFAULT 'none', "profile_completion_pct" integer NOT NULL DEFAULT '0', "role" character varying(20) NOT NULL DEFAULT 'user', "status" character varying(20) NOT NULL DEFAULT 'active', "onboarding_completed" boolean NOT NULL DEFAULT false, "notifications_enabled" boolean NOT NULL DEFAULT false, "email_verified_at" TIMESTAMP WITH TIME ZONE, "phone_verified_at" TIMESTAMP WITH TIME ZONE, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5a59b0826103ff324dcbc394fbd" PRIMARY KEY ("cz_user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ed3378bcf1d4dc65bd12abaa29" ON "cz_users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9ee94422dde77634b5cb2ffcee" ON "cz_users" ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_020e2d983e859efdf012d034df" ON "cz_users" ("referral_code") `);
        await queryRunner.query(`CREATE TABLE "cz_user_streaks" ("cz_user_id" uuid NOT NULL, "current_day" integer NOT NULL DEFAULT '0', "longest_day" integer NOT NULL DEFAULT '0', "last_claimed_date" date, "streak_start_date" date, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1327c05afb37691b86ed3591e70" PRIMARY KEY ("cz_user_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_user_challenge_progress" ("cz_user_challenge_progress_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "challenge_id" uuid NOT NULL, "date" date NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "completed_at" TIMESTAMP WITH TIME ZONE, "claimed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1be5c9f2aedcaaa1b98cb757f42" PRIMARY KEY ("cz_user_challenge_progress_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36df75fea386c45f667374c0bc" ON "cz_user_challenge_progress" ("user_id", "challenge_id", "date") `);
        await queryRunner.query(`CREATE TABLE "cz_user_achievements" ("cz_user_achievement_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "achievement_id" uuid NOT NULL, "progress" integer NOT NULL DEFAULT '0', "unlocked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_65a2242f0faa05d1a84bbdbb9f1" PRIMARY KEY ("cz_user_achievement_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cbd2adf1510c15e6727c83744d" ON "cz_user_achievements" ("user_id", "achievement_id") `);
        await queryRunner.query(`CREATE TABLE "cz_support_tickets" ("cz_support_ticket_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying(20) NOT NULL, "category" character varying(60), "subject" character varying(255), "description" text NOT NULL, "rating" integer, "attachment_urls" jsonb NOT NULL DEFAULT '[]'::jsonb, "status" character varying(20) NOT NULL DEFAULT 'open', "admin_response" text, "resolved_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4e35a0494bf3529b2f0c7611af6" PRIMARY KEY ("cz_support_ticket_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_96a020fb0b0f7085fd6f26c908" ON "cz_support_tickets" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cz_streak_reward_configs" ("cz_streak_reward_config_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "day_number" integer NOT NULL, "reward_type" character varying(10) NOT NULL DEFAULT 'coins', "reward_amount" integer NOT NULL, CONSTRAINT "PK_654605592ecff31515f5541d565" PRIMARY KEY ("cz_streak_reward_config_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5e692ea012a53dcd5823c95d53" ON "cz_streak_reward_configs" ("day_number") `);
        await queryRunner.query(`CREATE TABLE "cz_spin_wheel_configs" ("cz_spin_wheel_config_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying(60) NOT NULL, "reward_coins" integer NOT NULL DEFAULT '0', "reward_gems" integer NOT NULL DEFAULT '0', "probability_weight" double precision NOT NULL DEFAULT '1', "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5a2c8c326c45975593671eb223d" PRIMARY KEY ("cz_spin_wheel_config_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_spin_history" ("cz_spin_history_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "config_id" uuid NOT NULL, "reward_coins" integer NOT NULL DEFAULT '0', "reward_gems" integer NOT NULL DEFAULT '0', "played_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_892e3dfb3e48dadae0a4720fedd" PRIMARY KEY ("cz_spin_history_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee42ce824ea8a66645b9c03965" ON "cz_spin_history" ("user_id", "played_at") `);
        await queryRunner.query(`CREATE TABLE "cz_scratch_history" ("cz_scratch_history_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "card_id" uuid NOT NULL, "reward_coins" integer NOT NULL DEFAULT '0', "reward_gems" integer NOT NULL DEFAULT '0', "played_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4feb99975047fafabe964161a63" PRIMARY KEY ("cz_scratch_history_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e41724c49d5d5f65a1b377fd6" ON "cz_scratch_history" ("user_id", "played_at") `);
        await queryRunner.query(`CREATE TABLE "cz_scratch_cards" ("cz_scratch_card_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "label" character varying(60) NOT NULL, "reward_coins" integer NOT NULL DEFAULT '0', "reward_gems" integer NOT NULL DEFAULT '0', "probability_weight" double precision NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d405feccbf2d346f39939c248e5" PRIMARY KEY ("cz_scratch_card_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_referrals" ("cz_referral_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "referrer_id" uuid NOT NULL, "referred_id" uuid NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "tier_reached" character varying(60), "reward_coins" integer NOT NULL DEFAULT '0', "qualified_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b488adb58c36208b80a27f89443" PRIMARY KEY ("cz_referral_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bf7c5d79443138c0cd79e49d61" ON "cz_referrals" ("referred_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1fb881956aa59f642184e9006" ON "cz_referrals" ("referrer_id") `);
        await queryRunner.query(`CREATE TABLE "cz_referral_tier_configs" ("cz_referral_tier_config_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invites_required" integer NOT NULL, "reward_type" character varying(60) NOT NULL, "reward_value" character varying(120) NOT NULL, "reward_coins" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_94c6fda79ea8e901615c3e90b42" PRIMARY KEY ("cz_referral_tier_config_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_88c9eddfd42975529f2ee18938" ON "cz_referral_tier_configs" ("invites_required") `);
        await queryRunner.query(`CREATE TABLE "cz_quizzes" ("cz_quiz_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "question" text NOT NULL, "options" jsonb NOT NULL, "correct_option" character varying(255) NOT NULL, "reward_coins" integer NOT NULL DEFAULT '0', "date" date NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5f8998118c215a6a2ae5aca1bfc" PRIMARY KEY ("cz_quiz_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a3beb09be1ce7744de44940d63" ON "cz_quizzes" ("date") `);
        await queryRunner.query(`CREATE TABLE "cz_quiz_attempts" ("cz_quiz_attempt_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "quiz_id" uuid NOT NULL, "selected_option" character varying(255) NOT NULL, "is_correct" boolean NOT NULL, "reward_coins" integer NOT NULL DEFAULT '0', "attempted_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_4200252b917dcd2967178d29fa7" PRIMARY KEY ("cz_quiz_attempt_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_28c64d9e6b92bc93597fc32d52" ON "cz_quiz_attempts" ("user_id", "quiz_id") `);
        await queryRunner.query(`CREATE TABLE "cz_otp_codes" ("cz_otp_code_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "channel" character varying(10) NOT NULL, "purpose" character varying(20) NOT NULL, "destination" character varying(255) NOT NULL, "code_hash" character varying(255) NOT NULL, "attempts" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "consumed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cd479a236c09ccaffd2b6d09505" PRIMARY KEY ("cz_otp_code_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e674f940daf10238eb83b92d05" ON "cz_otp_codes" ("destination", "purpose") `);
        await queryRunner.query(`CREATE TABLE "cz_offerwall_providers" ("cz_offerwall_provider_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(80) NOT NULL, "adapter_type" character varying(40) NOT NULL DEFAULT 'generic', "base_api_url" character varying(500) NOT NULL, "api_key_encrypted" text, "postback_secret" text, "field_mapping" jsonb NOT NULL, "macro_template" jsonb NOT NULL, "sync_interval_minutes" integer NOT NULL DEFAULT '30', "is_active" boolean NOT NULL DEFAULT true, "last_synced_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e437abece08150ad8b64cecae5e" PRIMARY KEY ("cz_offerwall_provider_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_offers" ("cz_offer_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_id" uuid NOT NULL, "external_offer_id" character varying(120) NOT NULL, "title" character varying(255) NOT NULL, "description" text, "image_url" character varying(500), "reward_coins" integer NOT NULL DEFAULT '0', "reward_gems" integer NOT NULL DEFAULT '0', "category" character varying(60), "countries" jsonb NOT NULL DEFAULT '[]'::jsonb, "platforms" jsonb NOT NULL DEFAULT '[]'::jsonb, "goals" jsonb NOT NULL DEFAULT '[]'::jsonb, "is_active" boolean NOT NULL DEFAULT true, "expires_at" TIMESTAMP WITH TIME ZONE, "synced_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_01b25bccab2177af19b748b0574" PRIMARY KEY ("cz_offer_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_08c45454b35cea9f5df8f9008a" ON "cz_offers" ("provider_id", "external_offer_id") `);
        await queryRunner.query(`CREATE TABLE "cz_offer_completions" ("cz_offer_completion_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "offer_click_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "external_transaction_id" character varying(120) NOT NULL, "goal_id" character varying(120), "payout_coins" integer NOT NULL DEFAULT '0', "status" character varying(20) NOT NULL DEFAULT 'pending', "raw_payload" jsonb NOT NULL, "credited_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0fead06e027dbc84d5c23ac6d74" PRIMARY KEY ("cz_offer_completion_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee7d09c677ac8425fee4b98e58" ON "cz_offer_completions" ("provider_id", "external_transaction_id") `);
        await queryRunner.query(`CREATE TABLE "cz_offer_clicks" ("cz_offer_click_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "offer_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "click_id" character varying(64) NOT NULL, "ip_address" character varying(64), "user_agent" character varying(500), "clicked_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_aa7371f892b7326be3115c288d8" PRIMARY KEY ("cz_offer_click_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6a1fa002dde0f67d8c0e278f77" ON "cz_offer_clicks" ("click_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6325a4a38cd7de45f0a3bbff4d" ON "cz_offer_clicks" ("user_id", "clicked_at") `);
        await queryRunner.query(`CREATE TABLE "cz_notifications" ("cz_notification_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "title" character varying(120) NOT NULL, "body" text NOT NULL, "type" character varying(20) NOT NULL DEFAULT 'in_app', "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_33f84f37888c9bdcf47b2610f4c" PRIMARY KEY ("cz_notification_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6988e91daf69c0d9e67e8fc082" ON "cz_notifications" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cz_lucky_draws" ("cz_lucky_draw_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(10) NOT NULL, "title" character varying(120) NOT NULL, "prize_pool_coins" integer NOT NULL, "entry_cost_gems" integer NOT NULL DEFAULT '1', "winners_count" integer NOT NULL DEFAULT '1', "draw_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_0a70e549684e0c6ecd4b956a3eb" PRIMARY KEY ("cz_lucky_draw_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_lucky_draw_winners" ("cz_lucky_draw_winner_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "draw_id" uuid NOT NULL, "user_id" uuid NOT NULL, "prize_amount" integer NOT NULL, "rank" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_953189db8802df2e23c26b74fd9" PRIMARY KEY ("cz_lucky_draw_winner_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2b7ccda6ab55efa0ef51b047d5" ON "cz_lucky_draw_winners" ("draw_id") `);
        await queryRunner.query(`CREATE TABLE "cz_lucky_draw_entries" ("cz_lucky_draw_entry_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "draw_id" uuid NOT NULL, "entries_count" integer NOT NULL DEFAULT '1', "gems_spent" integer NOT NULL DEFAULT '0', "purchased_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c8de7a38d6152c278233eb932b0" PRIMARY KEY ("cz_lucky_draw_entry_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_287fce32213b9aad516b1440cf" ON "cz_lucky_draw_entries" ("draw_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "cz_kyc_verifications" ("cz_kyc_verification_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "selfie_url" character varying(500) NOT NULL, "rekognition_score" double precision, "rekognition_response" jsonb, "status" character varying(20) NOT NULL DEFAULT 'pending', "rejection_reason" text, "reviewed_by" uuid, "reviewed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_00f0aabcead9a516507e9a53037" PRIMARY KEY ("cz_kyc_verification_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ef8606f468fb4c1d172dc32b6" ON "cz_kyc_verifications" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cz_gift_card_products" ("cz_gift_card_product_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_name" character varying(60) NOT NULL, "external_product_id" character varying(120) NOT NULL, "brand" character varying(120) NOT NULL, "denomination" character varying(20) NOT NULL, "price_coins" integer NOT NULL, "category" character varying(60), "image_url" character varying(500), "is_featured" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "synced_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_b2f670ab95c5c848aa26a112568" PRIMARY KEY ("cz_gift_card_product_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7ea1d146a17989c776aaa5a6e5" ON "cz_gift_card_products" ("provider_name", "external_product_id") `);
        await queryRunner.query(`CREATE TABLE "cz_gift_card_orders" ("cz_gift_card_order_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "product_id" uuid NOT NULL, "price_coins" integer NOT NULL, "provider_order_id" character varying(120), "redeemed_code_encrypted" text, "status" character varying(20) NOT NULL DEFAULT 'pending', "failure_reason" text, "fulfilled_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e6120ebf9a7a47375e4eb93ec64" PRIMARY KEY ("cz_gift_card_order_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ef54315e49801fbb4d7fd120d" ON "cz_gift_card_orders" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cz_faqs" ("cz_faq_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "category_id" uuid NOT NULL, "question" character varying(255) NOT NULL, "answer" text NOT NULL, "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_18dd7b8a87846cd2e66e13acb35" PRIMARY KEY ("cz_faq_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1fa748683dea75827e05c93970" ON "cz_faqs" ("category_id") `);
        await queryRunner.query(`CREATE TABLE "cz_faq_categories" ("cz_faq_category_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(80) NOT NULL, "icon" character varying(120), "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_af6bb9c6d2bf7b4ec88013ac319" PRIMARY KEY ("cz_faq_category_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_daily_checkins" ("cz_daily_checkin_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "date" date NOT NULL, "streak_count" integer NOT NULL DEFAULT '1', "reward_coins" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6678e3fb51e4d30cc3f1145e7ea" PRIMARY KEY ("cz_daily_checkin_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3e5e6fa4a2584e3666e041515b" ON "cz_daily_checkins" ("user_id", "date") `);
        await queryRunner.query(`CREATE TABLE "cz_daily_challenges" ("cz_daily_challenge_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying(20) NOT NULL, "title" character varying(120) NOT NULL, "description" character varying(255), "reward_coins" integer NOT NULL DEFAULT '0', "reward_gems" integer NOT NULL DEFAULT '0', "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_4761a36a30eb469c1fbafb5319d" PRIMARY KEY ("cz_daily_challenge_id"))`);
        await queryRunner.query(`CREATE TABLE "cz_cron_job_logs" ("cz_cron_job_log_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "job_name" character varying(80) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'running', "last_run_at" TIMESTAMP WITH TIME ZONE NOT NULL, "next_run_at" TIMESTAMP WITH TIME ZONE, "duration_ms" integer, "error_message" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c83210d77eb8ccf13f8b4e753fd" PRIMARY KEY ("cz_cron_job_log_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_304a7384290a3be87238ab679a" ON "cz_cron_job_logs" ("job_name", "created_at") `);
        await queryRunner.query(`CREATE TABLE "cz_app_settings" ("setting_key" character varying(80) NOT NULL, "setting_value" text NOT NULL, "description" character varying(255), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a6d25c0809154b17f614a49ce83" PRIMARY KEY ("setting_key"))`);
        await queryRunner.query(`CREATE TABLE "cz_admin_users" ("cz_admin_user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "name" character varying(120), "role" character varying(20) NOT NULL DEFAULT 'support_agent', "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ae15beb2836bd056ece782eae43" PRIMARY KEY ("cz_admin_user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_13044b22211bf526d3befeb5ee" ON "cz_admin_users" ("email") `);
        await queryRunner.query(`CREATE TABLE "cz_achievements" ("cz_achievement_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying(120) NOT NULL, "description" text, "category" character varying(60), "icon_url" character varying(60), "criteria_type" character varying(60) NOT NULL, "criteria_value" integer NOT NULL DEFAULT '1', "points" integer NOT NULL DEFAULT '0', "reward_coins" integer NOT NULL DEFAULT '0', "rarity" character varying(20) NOT NULL DEFAULT 'common', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_99fe49033b1c71048470576d402" PRIMARY KEY ("cz_achievement_id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "cz_achievements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13044b22211bf526d3befeb5ee"`);
        await queryRunner.query(`DROP TABLE "cz_admin_users"`);
        await queryRunner.query(`DROP TABLE "cz_app_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_304a7384290a3be87238ab679a"`);
        await queryRunner.query(`DROP TABLE "cz_cron_job_logs"`);
        await queryRunner.query(`DROP TABLE "cz_daily_challenges"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3e5e6fa4a2584e3666e041515b"`);
        await queryRunner.query(`DROP TABLE "cz_daily_checkins"`);
        await queryRunner.query(`DROP TABLE "cz_faq_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fa748683dea75827e05c93970"`);
        await queryRunner.query(`DROP TABLE "cz_faqs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ef54315e49801fbb4d7fd120d"`);
        await queryRunner.query(`DROP TABLE "cz_gift_card_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ea1d146a17989c776aaa5a6e5"`);
        await queryRunner.query(`DROP TABLE "cz_gift_card_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ef8606f468fb4c1d172dc32b6"`);
        await queryRunner.query(`DROP TABLE "cz_kyc_verifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_287fce32213b9aad516b1440cf"`);
        await queryRunner.query(`DROP TABLE "cz_lucky_draw_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b7ccda6ab55efa0ef51b047d5"`);
        await queryRunner.query(`DROP TABLE "cz_lucky_draw_winners"`);
        await queryRunner.query(`DROP TABLE "cz_lucky_draws"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6988e91daf69c0d9e67e8fc082"`);
        await queryRunner.query(`DROP TABLE "cz_notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6325a4a38cd7de45f0a3bbff4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a1fa002dde0f67d8c0e278f77"`);
        await queryRunner.query(`DROP TABLE "cz_offer_clicks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee7d09c677ac8425fee4b98e58"`);
        await queryRunner.query(`DROP TABLE "cz_offer_completions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08c45454b35cea9f5df8f9008a"`);
        await queryRunner.query(`DROP TABLE "cz_offers"`);
        await queryRunner.query(`DROP TABLE "cz_offerwall_providers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e674f940daf10238eb83b92d05"`);
        await queryRunner.query(`DROP TABLE "cz_otp_codes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28c64d9e6b92bc93597fc32d52"`);
        await queryRunner.query(`DROP TABLE "cz_quiz_attempts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3beb09be1ce7744de44940d63"`);
        await queryRunner.query(`DROP TABLE "cz_quizzes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88c9eddfd42975529f2ee18938"`);
        await queryRunner.query(`DROP TABLE "cz_referral_tier_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1fb881956aa59f642184e9006"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf7c5d79443138c0cd79e49d61"`);
        await queryRunner.query(`DROP TABLE "cz_referrals"`);
        await queryRunner.query(`DROP TABLE "cz_scratch_cards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e41724c49d5d5f65a1b377fd6"`);
        await queryRunner.query(`DROP TABLE "cz_scratch_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee42ce824ea8a66645b9c03965"`);
        await queryRunner.query(`DROP TABLE "cz_spin_history"`);
        await queryRunner.query(`DROP TABLE "cz_spin_wheel_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e692ea012a53dcd5823c95d53"`);
        await queryRunner.query(`DROP TABLE "cz_streak_reward_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96a020fb0b0f7085fd6f26c908"`);
        await queryRunner.query(`DROP TABLE "cz_support_tickets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbd2adf1510c15e6727c83744d"`);
        await queryRunner.query(`DROP TABLE "cz_user_achievements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36df75fea386c45f667374c0bc"`);
        await queryRunner.query(`DROP TABLE "cz_user_challenge_progress"`);
        await queryRunner.query(`DROP TABLE "cz_user_streaks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_020e2d983e859efdf012d034df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ee94422dde77634b5cb2ffcee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed3378bcf1d4dc65bd12abaa29"`);
        await queryRunner.query(`DROP TABLE "cz_users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41210ef08979d6b04c49926426"`);
        await queryRunner.query(`DROP TABLE "cz_wallet_transactions"`);
        await queryRunner.query(`DROP TABLE "cz_wallets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38355efd1f960a92fd9bdaa302"`);
        await queryRunner.query(`DROP TABLE "cz_withdrawal_requests"`);
    }

}
