/**
 * One-off: seeds RewardTym's own offerwall as an offerwall_partners row.
 * Pass the lt_live_ api_key and postback_secret generated by
 * rewardtym-backend/scripts/onboard-coinzu-partner.ts as env vars.
 *
 * Run from project root:
 *   REWARDTYM_PARTNER_API_KEY=lt_live_... REWARDTYM_POSTBACK_SECRET=... \
 *   npx ts-node -r tsconfig-paths/register scripts/onboard-rewardtym-offerwall.ts
 */
import 'dotenv/config';
import { DataSource } from 'typeorm';

const dataSource = new DataSource({
  type: 'postgres',
  url: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

async function run() {
  const partner_api_key = process.env.REWARDTYM_PARTNER_API_KEY;
  const postback_secret = process.env.REWARDTYM_POSTBACK_SECRET;
  if (!partner_api_key || !postback_secret) {
    console.error('Set REWARDTYM_PARTNER_API_KEY and REWARDTYM_POSTBACK_SECRET.');
    process.exit(1);
  }

  await dataSource.initialize();

  try {
    const existing = await dataSource.query('SELECT cz_offerwall_partner_id FROM offerwall_partners WHERE slug = $1', [
      'rewardtym',
    ]);
    if (existing.length > 0) {
      console.log(`Partner already exists: rewardtym (${existing[0].cz_offerwall_partner_id})`);
      console.log('Not creating a duplicate. Delete the row first if you want to reseed it.');
      return;
    }

    const postback_field_mapping = {
      user_id: 'user_id',
      external_transaction_id: 'conversion_id',
      offer_name: 'campaign_name',
      payout: 'payout_amount',
      status: 'status',
      approved_value: 'approved',
      reversed_value: 'reversed',
    };

    const result = await dataSource.query(
      `INSERT INTO offerwall_partners
        (name, slug, description, click_url_template, integration_type, partner_api_key,
         postback_method, postback_auth_type, postback_secret, postback_field_mapping,
         coins_per_payout_unit, rank, badge_label, is_active)
       VALUES ($1, $2, $3, '', 'rewardtym_auth_code', $4, 'get', 'token', $5, $6, 1, 100, 'Trending', true)
       RETURNING cz_offerwall_partner_id`,
      [
        'RewardTym',
        'rewardtym',
        'Surveys, offers and app installs.',
        partner_api_key,
        postback_secret,
        JSON.stringify(postback_field_mapping),
      ],
    );

    console.log('RewardTym offerwall partner created in Coinzu.');
    console.log('cz_offerwall_partner_id:', result[0].cz_offerwall_partner_id);
  } finally {
    await dataSource.destroy();
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
