/**
 * One-off: seeds RewardTym's own offerwall as an offerwall_partners row.
 * Pass the postback_secret generated by rewardtym-backend/scripts/onboard-coinzu-partner.ts
 * and the wall URL (with {USER_ID} where the Coinzu user id goes) as env vars.
 * Re-running fills in the URL of an existing row that was seeded without one.
 *
 * Run from project root:
 *   REWARDTYM_WALL_URL='https://.../wall?user_id={USER_ID}' REWARDTYM_POSTBACK_SECRET=... \
 *   npx ts-node -r tsconfig-paths/register scripts/onboard-rewardtym-offerwall.ts
 */
import 'dotenv/config';
import { DataSource } from 'typeorm';

const dataSource = new DataSource({
  type: 'postgres',
  url: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

async function run() {
  const wall_url = process.env.REWARDTYM_WALL_URL;
  const postback_secret = process.env.REWARDTYM_POSTBACK_SECRET;
  if (!wall_url?.includes('{USER_ID}') || !postback_secret) {
    console.error('Set REWARDTYM_WALL_URL (containing {USER_ID}) and REWARDTYM_POSTBACK_SECRET.');
    process.exit(1);
  }

  await dataSource.initialize();

  try {
    const existing = await dataSource.query('SELECT cz_offerwall_partner_id FROM offerwall_partners WHERE slug = $1', [
      'rewardtym',
    ]);
    if (existing.length > 0) {
      await dataSource.query('UPDATE offerwall_partners SET click_url_template = $1 WHERE slug = $2', [wall_url, 'rewardtym']);
      console.log(`Partner already exists: rewardtym (${existing[0].cz_offerwall_partner_id}). Wall URL updated.`);
      return;
    }

    const postback_field_mapping = {
      user_id: 'user_id',
      external_transaction_id: 'conversion_id',
      offer_name: 'campaign_name',
      payout: 'payout_amount',
      status: 'status',
      approved_value: 'approved',
      reversed_value: 'reversed',
    };

    const result = await dataSource.query(
      `INSERT INTO offerwall_partners
        (name, slug, description, click_url_template,
         postback_method, postback_auth_type, postback_secret, postback_field_mapping,
         coins_per_payout_unit, rank, badge_label, is_active)
       VALUES ($1, $2, $3, $4, 'get', 'token', $5, $6, 1, 100, 'Trending', true)
       RETURNING cz_offerwall_partner_id`,
      [
        'RewardTym',
        'rewardtym',
        'Surveys, offers and app installs.',
        wall_url,
        postback_secret,
        JSON.stringify(postback_field_mapping),
      ],
    );

    console.log('RewardTym offerwall partner created in Coinzu.');
    console.log('cz_offerwall_partner_id:', result[0].cz_offerwall_partner_id);
  } finally {
    await dataSource.destroy();
  }
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
